# Generated by Django 4.2 on 2024-09-21 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('doors', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('milage', models.DecimalField(decimal_places=1, max_digits=6)),
                ('range', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hand_drive', models.CharField(max_length=50)),
                ('wheels_drive', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brokers.broker')),
            ],
        ),
    ]
